### ISSUE TITLE
Yay, progress!

### ISSUE THREAD

**Issue by andreas-groos** [thosmos/riverdb#27]
Congratulations @thosmos on fixing some bugs. Bummer that SYRCL cancelled the cleanup.

**Comment by thosmos** [comment]
Congrats on the first issue!  Why did they cancel the cleanup?  Care to mention another bug that most needs fixing?

**Comment by andreas-groos** [comment]
Because of the smoke conditions. I was out of town.
I don't know, haven't had a look in a long time.
