### ISSUE TITLE
SSI RiverDB questions

### ISSUE THREAD

**Issue by SierraStreamsInstitute-Lab** [thosmos/riverdb#28]
Hi Thomas, 

We would like to make a few changes to the way that data is entered on the SSI RiverDB projects, and I wanted to check that these changes would not impact previously entered data. These are some of the things we would like to do:

1. Enter 3 readings for Turbidity. Currently we have it set up to enter 9 measurements, 3 for each Turbidity 1, 2, and 3.
2. Move Nitrate and Phosphate lab results from the field measurements section to the  lab results section. I would also like to make sure that it would be possible to enter 3 readings for each nutrient. We run 3 replicates in our lab.

**Comment by thosmos** [comment]
1) If I understand that you want to use it going forward with only 3 values.  It was not designed with the 9 value use case, so I would prefer to go back and change those to 3 values.  But if you are sure you want to keep those older 9 values, the best thing to do would be to add a new fourth Turbidity parameter and use that for the new 3 values.  

2) I'll need to add support for multiple sample replicates to the lab results.  This was designed for a remote lab that generally just reports a single value.  I'm curious why you want to move them to the lab section other than just the labeling?

**Comment by thosmos** [comment]
Answered in another issue https://github.com/thosmos/riverdb/issues/34
