### ISSUE TITLE
SSI Turbidity Data Entry

### ISSUE THREAD

**Issue by SierraStreamsInstitute-Lab** [thosmos/riverdb#34]
Instead of having three turbidity entries, each with three replicates, in the field measurements, we would like to have one entry with our median values. I switched the turbidity 2 and turbidity 3 values from "true" to "false" in the admin section. These values are no longer showing up in the public facing data entries. Only the turbidity 1 values are showing up on all of the previously entered data sheets. Will we have to go back one by one now and update these to the median values or is there a way to bulk upload this data?

**Comment by thosmos** [comment]
Oh good, I responded to your earlier issue suggesting this router.  I think this is the best way to move forward.  For now this is a manual process. I intend to update the bulk import feature to be able to overwrite old values, but for now it's only for bringing in new data.
