### ISSUE TITLE
SSI - only SYRCL projects are options to link a station to 

### ISSUE THREAD

**Issue by SierraStreamsInstitute-Lab** [thosmos/riverdb#39]
We have begun monitoring at a few new locations and would like to add these to RiverDB. How can we add new locations?

**Comment by thosmos** [comment]
Under the admin dropdown, there is the "stations" view which enables adding new stations.  Do you see the "admin" menu when you're logged in?  If not, your user login might not have admin privileges and so the admin of your organization would need to do it or they can grant you that access level.

**Comment by SierraStreamsInstitute-Lab** [comment]
![Add station](https://user-images.githubusercontent.com/114112659/217945898-bb4f18ab-d779-48c9-b366-87e9e0629625.png)
[](url)
I do have admin privileges but when I add a station only SYRCL projects come up to attribute it to.

**Comment by thosmos** [comment]
Oh!  Ok sounds like a bug.  I’ll look into it.

**Comment by thosmos** [comment]
Fixed in the latest build v1.0.27 #9156c0daf3340491ff70c307aafcccf2df075b8e
