### ISSUE TITLE
Bulk upload

### ISSUE THREAD

**Issue by SierraStreamsInstitute-Lab** [thosmos/riverdb#45]
As we're gearing up for our annual TAC meeting, and the updates are not yet ready, I was hoping to just bulk upload our 2022 data so we could get our QA/QC metrics. However, I'm not able to do any bulk uploads, despite following the guide that Alex wrote. 
![RiverDB bulk upload error](https://user-images.githubusercontent.com/114112659/228681443-581280c3-78d0-4ecc-991d-1dce4e2bc2da.jpg)
[BR site 1 RiverDB upload 2022-2023.csv](https://github.com/thosmos/riverdb/files/11106080/BR.site.1.RiverDB.upload.2022-2023.csv)

**Comment by thosmos** [comment]
The bugs in the importer have been fixed.
